# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scripter-Plugin-JavaScript
version:      0.008
version_from: lib/WWW/Scripter/Plugin/JavaScript.pm
installdirs:  site
requires:
    Carp:                          0
    CSS::DOM::Interface:           0
    Encode:                        0
    Hash::Util::FieldHash::Compat: 0
    HTML::DOM:                     0.027
    HTML::DOM::EventTarget:        0.032
    HTML::DOM::Interface:          0.032
    JE:                            0.038
    JE::Destroyer:                 0
    lib:                           0
    LWP::UserAgent:                5.815
    Scalar::Util:                  1.09
    strict:                        0
    Test::More:                    0
    URI::Escape:                   0
    URI::file:                     0
    warnings:                      0
    WWW::Scripter:                 0.022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
