# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scripter-Plugin-JavaScript
version:      0.002c
version_from: 
installdirs:  site
requires:
    Carp:                          0
    CSS::DOM::Interface:           0
    Encode:                        0
    Hash::Util::FieldHash::Compat: 0
    HTML::DOM:                     0.027
    HTML::DOM::Interface:          0
    JE:                            0.022
    lib:                           0
    LWP::UserAgent:                5.815
    Scalar::Util:                  0
    strict:                        0
    Test::More:                    0
    URI::Escape:                   0
    URI::file:                     0
    warnings:                      0
    WWW::Scripter:                 0.004

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
